name: Health check

on:
  schedule:
    - cron: '30 23 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: https://muddy-thunder-3474-icy-shape-7791.fly.dev/health